language: python

python:
    - "2.7"

before_install:
    - sudo apt-get install python-dev
    - pip install nose flake8 fabric
    - python setup.py install

script:
    - fab reset
    - make lint && make test

after_success:
    - pip install coveralls
    - coverage run --source=fbone setup.py -q nosetests
    - coveralls

notifications:
    email: false
